# Generated by Django 5.0.6 on 2024-10-05 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('poster', models.CharField(max_length=255)),
                ('directors', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('cast', models.TextField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('ratingCategory', models.CharField(blank=True, max_length=5, null=True)),
                ('genre', models.TextField()),
                ('description', models.TextField()),
                ('availableFrom', models.DateField()),
                ('availableTo', models.DateField()),
                ('timings', models.TextField()),
                ('availableLocations', models.TextField()),
                ('availableScreens', models.TextField()),
                ('releaseDate', models.DateField()),
                ('duration', models.TimeField()),
                ('language', models.TextField()),
                ('trailer', models.URLField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dimensional', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('show_date', models.DateField()),
                ('show_time', models.TimeField()),
                ('movie_language', models.CharField(max_length=50)),
                ('location_selected', models.CharField(max_length=100)),
                ('seats_selected', models.CharField(max_length=255)),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
        ),
    ]
